#!/bin/bash

# install remaing hero
# apt-get install herokuish -y
docker pull gliderlabs/herokuish

mkdir -p /root/.ssh
cat /root/.ssh/authorized_keys | sshcommand acl-add dokku admin
echo $VHOSTNAME > /home/dokku/VHOST

/usr/bin/supervisord
